version: "3.8"
services:
  website:
    build: ./website
    ports: 
      - 8000:8000
    volumes: 
      - ./website/src:/the-website/src/
    expose:
      - 6379
    depends_on: 
      - db
      - redis
      - postgressDb
    environment:
      DB_HOST: db
      REDIS_HOST: redis
    networks: 
      - webnet

  db:
    build: ./db
    ports:
      - 3306:3306
    environment: 
      MYSQL_ROOT_PASSWORD: abc123
      MYSQL_DATABASE: hello
    networks:
      - webnet

  redis:
    image: "redis"
    ports: 
      - 6379:6379
    networks:
      - webnet

  postgressDb:
    build: ./postgressDb
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: abc123
      POSTGRES_DB: hello
      POSTGRES_USERNAME: root
    ports: 
      - 5432:5432
    networks: 
      - webnet

  nginx:
    build: ./spa
    ports: 
      - 8080:80
    networks: 
      - webnet
    
   
networks:
  webnet:
    
    

