version: "3.8"
services:
  website:
    build: ./website
    ports: 
      - 8000:8000
    volumes: 
      - ./website/src:/the-website/src/
    depends_on: 
      - db
  db:
    build: ./db
    ports:
    - 3306:3306
    environment: 
      MYSQL_ROOT_PASSWORD: abc123
      MYSQL_DATABASE: hello
