version: "3.8"
services:
  website:
    build: ./website
    ports: 
      - 8000:8000
    volumes: 
      - ./website/src:/the-website/src/
    depends_on: 
      - db
      - redis
    environment: 
      DB_HOST: db
      REDIS_HOST: redis
  db:
    build: ./db
    ports:
    - 3306:3306
    environment: 
      MYSQL_ROOT_PASSWORD: abc123
      MYSQL_DATABASE: hello
  redis:
    image: "redis"
    ports:
      - 6380:6380
    
    

