CREATE TABLE  IF NOT EXISTS user(
    id INT AUTO_INCREMENT,
    username VARCHAR(50) NOT NULL ,
    name VARCHAR(50) NOT NULL, 
    password VARCHAR(50) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS feedBack(
    id INT AUTO_INCREMENT,
    userId INT NOT NULL,
    title VARCHAR(50),
    content VARCHAR(400),
    PRIMARY KEY (id),
    FOREIGN KEY (userId) REFERENCES user(id) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS comment(
    id INT AUTO_INCREMENT,
    feedBackId INT NOT NULL,
    userId INT NOT NULL,
    content VARCHAR(400),
    PRIMARY KEY (id),
    FOREIGN KEY (feedBackId) REFERENCES feedBack(id) ON DELETE CASCADE,
    FOREIGN KEY (userId) REFERENCES user(id) ON DELETE CASCADE
);


